version: "3.5"
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/work
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.gnupg:/root/.gnupg

    working_dir: /work
    networks:
      - default
    ports:
      - "127.0.0.1:5678:5678"
      - "127.0.0.1:9678:9678"
      - "127.0.0.1:9876:9876"
      - "127.0.0.1:9757:9757"
    depends_on:
      - db
    command: nginx -c /workspaces/PermissionHub/reverseproxy/nginx.conf && sleep infinity

  db:
    image: postgres:12
    working_dir: /
    volumes:
      - db-volume:/var/lib/postgresql/data
      - ./data:/data
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "127.0.0.1:6543:5432"
    restart: unless-stopped
    networks:
      - default
    command:
      postgres -c logging_collector=on -c log_destination=stderr -c
      log_directory=/var/lib/postgresql/data/logs -c log_rotation_age=60 -c
      log_truncate_on_rotation=on -c log_filename=server_log.hour.%H%M

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db
    environment:
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_DEFAULT_EMAIL=lukas@statuscode.ch
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PREFIX_COUNT=1

volumes:
  db-volume:
